spring:
  threads:
    virtual:
      enabled: true

  datasource: #Config MySQL for relationship database
    url: jdbc:mysql://localhost:3306/einvoice_db?createDatabaseIfNotExist=true
    username: root
    password: HK040103
    drive-class-name: com.mysql.cj.jdbc.Driver

  data:       #Config MongoDB for no-sql database
    mongodb:
        uri: mongodb://localhost:27017/einvoice_logs

  jpa:
    hibernate:
      ddl-auto: update #Auto create table from Entity Class
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:org.hibernate.dialect.MySQL8Dialect


  #application:
    #name: einvoice-core