spring:
  threads:
    virtual:
      enabled: true

  datasource: #Config MySQL for relationship database
    url: jdbc:mysql://localhost:3306/einvoicehub?createDatabaseIfNotExist=true
    username: root
    password:
    drive-class-name: com.mysql.cj.jdbc.Driver

  data:       #Config MongoDB for no-sql database
    mongodb:
        uri: 'mongodb+srv://huykyunhk:HuyKyunH.K07@cluster0.17bgl.mongodb.net/einvoicehub'


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:org.hibernate.dialect.MySQL8Dialect


  #application:
    #name: einvoice-core